version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - kohsmic_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - kohsmic_static:/data/static/
      - kohsmic_media:/data/media/


  django:
    image: kohsmic_django:5
    networks:
      - kohsmic_network
    volumes:
      - kohsmic_static:/home/test11/staticfiles/
      - kohsmic_media:/home/test11/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - kohsmic_network
    volumes:
    - kohsmic_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: 1234
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD


networks:
  kohsmic_network:

volumes:
  kohsmic_static:
  kohsmic_media:
  kohsmic_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true